version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  sonar:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  version: 2
  code-quality:
    jobs:
      - sonar:
          context: sonarcloud