
base_url = "https://base.nocheyniebla.org/consulta_web.php"
raw_data = "evita_csrf=%2FEl5dGqjXZgB%2B%2FAf33srYw%3D%3D&_qf_default=consultaWeb%3Aconsulta&titulo=&id_departamento=76&id_municipio=&nomvic=&sexo=&fini%5Bd%5D=&fini%5BM%5D=&fini%5BY%5D=&ffin%5Bd%5D=&ffin%5BM%5D=&ffin%5BY%5D=&presponsable=&contexto=&clasificacion%5B%5D=A%3A1%3A10&ssocial=1&descripcion=&critetiqueta=0&poretiqueta=&critetiqueta2=0&poretiqueta2=&ordenar=fecha&mostrar=tabla&caso_memo=1&caso_fecha=1&m_ubicacion=1&m_victimas=1&m_presponsables=1&m_tipificacion=1&_qf_consultaWeb_consulta=Consulta"
patternVictims = r'(,[\s]{1,2}\b[^\d\W]+\b)|(,\sN\sN)'
patternActsVictim = r'(\s[A-Z]{1,2}\d{1,4}|,\s[A-Z]{1,2}\d{1,4})'
data = {
    "evita_csrf":"uZH0XdSsJW9uwS24ZQLrdg==",
    "presponsable":"103",
    "ffin[M]":"",
    "ffin[d]":"",
    "descripcion":"",
    "caso_memo":"1",
    "tabla":"",
    "m_victimas":"1",
    "mostrar":"",
    "fini[d]":"",
    "m_tipificacion":"1",
    "_qf_consultaWeb_consulta":"Consulta",
    "titulo":"",
    "nomvic":"",
    "sexo":"",
    "m_ubicacion":"1",
    "ssocial":"",
    "fini[Y]":"",
    "id_departamento":"76",
    "id_municipio":"616",
    "caso_fecha":"1",
    "ordenar":"fecha",
    "fini[M]":"",
    "contexto":"",
    "ffin[Y]":"",
    "_qf_default:consultaWeb":"consultaic=",
    "sexo":"",
    "fini[d]":"",
    "fini[M]":"",
    "fini[Y]":"",
    "ffin[d]":"",
    "ffin[M]":"",
    "ffin[Y]":"",
    "presponsable":"103",
    "contexto":"",
    "ssocial":"",
    "descripcion":"",
    "ordenar":"fecha",
    "mostrar":"tabla",
    "caso_memo":"1",
    "caso_fecha":"1",
    "m_ubicacion":"1",
    "m_victimas":"1",
    "m_presponsables":"1",
    "m_tipificacion":"1"
}